export const breeds = [
  "Akita",
  "Basset Hound",
  "Beagle",
  "Border Collie",
  "Boxer",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Chihuahua",
  "Cocker Spaniel",
  "Dachshund",
  "Doberman",
  "Fila Brasileiro",
  "Golden Retriever",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lhasa Apso",
  "Maltês",
  "Pastor Alemão",
  "Pinscher",
  "Pit Bull",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Shih Tzu",
  "Spitz Alemão",
  "Vira-lata (SRD)",
  "Weimaraner",
  "Yorkshire Terrier",
  "Outra raça"
].sort();
